apiVersion: v1
items:
- apiVersion: autoscaling/v2beta2
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: "2021-02-23T07:01:39Z"
    managedFields:
    - apiVersion: autoscaling/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:maxReplicas: {}
          f:minReplicas: {}
          f:scaleTargetRef:
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
          f:targetCPUUtilizationPercentage: {}
      manager: kubectl-autoscale
      operation: Update
      time: "2021-02-23T07:01:39Z"
    - apiVersion: autoscaling/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:autoscaling.alpha.kubernetes.io/conditions: {}
            f:autoscaling.alpha.kubernetes.io/current-metrics: {}
        f:status:
          f:currentCPUUtilizationPercentage: {}
          f:currentReplicas: {}
          f:desiredReplicas: {}
          f:lastScaleTime: {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-02-23T07:03:10Z"
    name: go-runner
    namespace: default
    resourceVersion: "2293"
    uid: a5e38a7d-5a17-46f3-9091-c7ab65750545
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: go-runner
  status:
    conditions:
    - lastTransitionTime: "2021-02-23T07:01:54Z"
      message: recent recommendations were higher than current one, applying the highest
        recent recommendation
      reason: ScaleDownStabilized
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2021-02-23T07:03:10Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2021-02-23T07:03:26Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 0
          averageValue: 1m
        name: cpu
      type: Resource
    currentReplicas: 5
    desiredReplicas: 5
    lastScaleTime: "2021-02-23T07:03:26Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
