apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-runner
spec:
  selector:
    matchLabels:
      app: go-runner
  template:
    metadata:
      labels:
        app: go-runner
    spec:
      containers:
      - name: go-runner
        image: primozh/hpa-example
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-runner
spec:
  selector:
    app: go-runner
  ports:
  - port: 80
    targetPort: 8080
