apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-runner
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-runner
  targetCPUUtilizationPercentage: 50