apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
---
apiVersion: v1
kind: Pod
metadata:
  name: static-client
  labels:
    name: static-client
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
    "consul.hashicorp.com/connect-service-upstreams": "static-server:1234"
spec:
  containers:
    - name: static-client
      image: tutum/curl:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: [ "/bin/sh", "-c", "--" ]
      args:
        - "while true; do sleep 30; done"
  serviceAccountName: static-client