apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-server
---
apiVersion: v1
kind: Pod
metadata:
  name: static-server
  labels:
    name: static-server
  annotations:
    "consul.hashicorp.com/connect-inject": "true"
spec:
  containers:
  - name: static-server
    image: hashicorp/http-echo:latest
    args:
      - -text="hello world"
      - -listen=:8080
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  serviceAccountName: static-server